language: c
compiler: gcc
env:
  global:
    - CODECOV_TOKEN=77057570-d7ed-4e6b-97a5-3c806393aac9

before_install:
- make get-deps

after_success:
  - bash <(curl -s https://codecov.io/bash)

script: 
  - make test
